@startuml
start

:拉取最近聊天卡片;
:展示聊天卡片;
fork
    :拉取部分聊天消息;
    detach
fork again
    split
        :创建聊天;
        :搜索添加用户;
        :设置聊天选项;
    split again
        :搜索查找聊天;
    end split
end fork

split
    :移除聊天卡片;
split again
    :进入聊天;
    split
        :展示消息;
    split again
        :更改聊天设置;
        split
            :设置提醒;
        split again
            if (权限判断) then (yes)
                split
                    :修改群名称;
                split again
                    :修改群头像;
                split again
                    :添加群成员;
                end split
            else (no)
            endif
        split again
            :设置置顶;
        end split
    split again
        :发送消息;
    end split
split again
    :接收消息;
end split

stop
@enduml