@startuml

class APIGatewayHandler {
    + void cmdHandler(Context ctx)
    + void signInHandler(Context ctx)
    + void signUpHandler(Context ctx)
    + void sendSMSHandler(Context ctx)
}

class Dispatcher {
    Map<Integer, String> cmdRouter

    - void init()
    + void RegisterCmdRoute(int cmd, String svr)
    + String getCmdHandleSvr(int cmd)
    + byte[] dispatch(ServeRequest req, int cmd)
}

class ReverseProxyFactory {
    + void getReverseProxy(String url)
}

class ReverseProxy {
    + void serveHTTP(HttpResponseWriter rw, HttpRequest httpReq)
}

class ServeRequestFactory {
    + ServeRequest getServeRequest(HttpRequest httpReq)
}

class ServeRequest {
    + int64 userID
    + int64 deviceID
    + String requestID
    + String source
    + byte[] payload
}

class ServeResponse {
    + int statusCode
    + String msg
    + byte[] payload
}

'class MetricsEmitter {
'    + void emitCounter(Map<String, String> tags, String name, int value)
'    + void emitTimer(Map<String, String> tags, String name, int value)
'}

class ServeClient {
    + ServeResponse serve(ServeRequest req)
}

APIGatewayHandler o-- Dispatcher
APIGatewayHandler --> ReverseProxyFactory

ServeRequestFactory --> ServeRequest
ReverseProxyFactory --> ReverseProxy

'Dispatcher --> MetricsEmitter
Dispatcher --> ServeRequestFactory
Dispatcher --> ServeClient

ServeClient --> ServeRequest
ServeClient --> ServeResponse

@enduml