@startuml

start
:访问系统;
if (未注册) then (yes)
	:注册账号;
endif
:登录系统;
if (登录成功) then (yes)
	:使用系统;
else (no)
    stop
endif
if (功能系统) then (yes)
	split
        :查看用户信息;
        split
            :设置自身信息;
        split again
            :其他用户信息;
        end split
    split again
        :搜索;
        split
            :搜索用户;
        split again
            :搜索群聊;
        end split
    split again
        :聊天页面;
        split
            :查看消息;
            :查看消息已读状态;
        split again
            :发送消息;
            split
                :文本消息;
            split again
                :图片消息;
            split again
                :文件消息;
            end split
        split again
            :接收消息;
        end split
    split again
        :联系人页面;
        split
            :手机号搜索;
            :添加好友申请;
        split again
            :查看联系人;
        split again
            :管理添加请求;
        end split
    split again
        :查看组织架构;
        :团队成员列表;
    end split
else (no)
    :管理租户;
    split
        :管理租户内用户;
    split again
        :管理组织架构;
    end split
endif
stop

@enduml